apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  replicas: 2
  selector:
   matchLabels:
    app: myapp
    version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      volumes:
      - name: message
        hostPath:
          path: /tmp
      containers:
      - name: myapp
        image: looshen/docker.mylearn:v1.0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: message
          mountPath: /tmp/
        startupProbe:
          failureThreshold: 3
          exec:
            command: ['/bin/sh','-c','echo startupProbe > /tmp/message3']
          initialDelaySeconds: 20
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2
