apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  replicas: 2
  selector:
   matchLabels:
    app: myapp
    version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      volumes:
      - name: message
        hostPath:
          path: /tmp
      containers:
      - name: myapp
        image: registry.cn-hangzhou.aliyuncs.com/rosentest01/docker.mylearn:v1.0.8
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo postStart handler > /tmp/message1"]
          preStop:
            exec:
              command: ["/bin/sh","-c","echo preStop handler > /tmp/message2"]
        volumeMounts:
        - name: message
          mountPath: /tmp/
        ports:
        - containerPort: 8080
        startupProbe:
          failureThreshold: 3
          exec:
            command: ['/bin/sh','-c','echo startupProbe > /tmp/message3']
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: ready-nodeport
  labels:
    name: ready-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30880
  selector:
    app: myapp
