apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  replicas: 2
  selector:
   matchLabels:
    app: myapp
    version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      volumes:
      - name: message
        hostPath:
          path: /tmp
      containers:
      - name: myapp
        image: looshen/docker.mylearn:v1.0.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","echo preStop handler > /tmp/message2"]
        volumeMounts:
        - name: message
          mountPath: /tmp/
